//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Answer { get; set; }
        public bool IsFaq { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
