//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public int DiscountID { get; set; }
        public int UserID { get; set; }
        public string DiscountCode { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int DiscountPercent { get; set; }
        public bool IsUsed { get; set; }
        public int MaxDiscountValue { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
