//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public string TraceCode { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int Payable { get; set; }
        public bool IsFinaly { get; set; }
        public int PaymentWay { get; set; }
        public bool UseDiscountCode { get; set; }
        public bool IsSent { get; set; }
        public int DeliveryID { get; set; }
        public Nullable<int> DeliveryPrice { get; set; }
    
        public virtual DeliveryWays DeliveryWays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
