//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PageID { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public string HeadTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Url { get; set; }
    }
}
