//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBrand
    {
        public int PBID { get; set; }
        public int ProductID { get; set; }
        public int BrandID { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Products Products { get; set; }
    }
}
