//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sellers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int SellerID { get; set; }
        public string SellerFullName { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public bool IsAcceptedByAdmin { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<double> Point { get; set; }
        public int UserID { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
