//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DataLayer
{
    internal class BlogsMetaData
    {
        [Key]
        public int BlogID { get; set; }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "توضیح کوتاه")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string ShortDescription { get; set; }

        [AllowHtml]
        [Display(Name = "متن")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string Text { get; set; }

        [Display(Name = "تصویر")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string ImageName { get; set; }


        public string Author { get; set; }

        [Display(Name = "تگ ها")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string Tags { get; set; }


        public System.DateTime CreateDate { get; set; }


        public int Visit { get; set; }
    }

    [MetadataType(typeof(BlogsMetaData))]
    public partial class Blogs
    {

    }
}