//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class BrandsMetaData
    {
        [Key]
        public int BrandID { get; set; }
        [Display(Name = "عنوان برند")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string BrandTitle { get; set; }
        [Display(Name = "عکس")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string BrandImageName { get; set; }
    }
    [MetadataType(typeof(BrandsMetaData))]
    public partial class Brands
    {

    }
}