//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class DiscountsMetaData
    {
        public int DiscountID { get; set; }
        public int UserID { get; set; }

        [Display(Name = "کد تخفیف")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string DiscountCode { get; set; }

        [Display(Name = "تاریخ انقضا")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public System.DateTime ExpireDate { get; set; }

        [Display(Name = "درصد تخفیف")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public int DiscountPercent { get; set; }

        [Display(Name = "استفاده شده؟")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public bool IsUsed { get; set; }
    }
    [MetadataType(typeof(DiscountsMetaData))]
    public partial class Discounts
    {

    }
}