//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class SellersMetaData
    {
        [Key]
        public int SellerID { get; set; }

        [Display(Name = "نام فروشنده")]
        public string SellerFullName { get; set; }

        [Display(Name = "نام فروشگاه")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public string StoreName { get; set; }

        [Display(Name = "آدرس فروشگاه")]
        public string StoreAddress { get; set; }

        [Display(Name = "تلفن ثابت")]
        public string Telephone { get; set; }

        //[Display(Name = "ایمیل")]
        //[Required(ErrorMessage = "لطفا {0} وارد کنید")]
        //[EmailAddress(ErrorMessage = "ایمیل وارد شده معتبر نمی باشد!")]
        //public string Email { get; set; }

        [Display(Name = "تاریخ شروع")]
        public System.DateTime StartDate { get; set; }

        [Display(Name = "وضعیت")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public bool IsAcceptedByAdmin { get; set; }
    }
    [MetadataType(typeof(SellersMetaData))]
    public partial class Sellers
    {

    }
}