//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    internal class SpecialProductsMetaData
    {
        [Key]
        public int SPID { get; set; }
        public int ProductID { get; set; }

        [Display(Name = "از تاریخ")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public System.DateTime CreateDate { get; set; }

        [Display(Name = "تا تاریخ")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public System.DateTime ExpireDate { get; set; }

        [Display(Name = "فعال")]
        [Required(ErrorMessage = "لطفا {0} وارد کنید")]
        public bool IsActive { get; set; }
    }
    [MetadataType(typeof(SpecialProductsMetaData))]
    public partial class SpecialProducts
    {

    }
}